tools:
  - class_name: verl.tools.search_tool.SearchTool
    config:
      retrieval_service_url: http://127.0.0.1:8000/search
      num_workers: 32
      rate_limit: 32
      timeout: 30
    tool_schema:
      type: function
      function:
        name: search
        description: Search for relevant passages given a query.
        parameters:
          type: object
          properties:
            query_list:
              type: array
              item:
                type: string
              description: A list of search queries.
          required:
            - query_list
